### ISSUE TITLE
Test Connect Walled Button in CTO project

### ISSUE THREAD

**Issue by alexmazaltov** [alefinvest/CTO#6]

**Comment by alexmazaltov** [comment]
@execodess please comment with screenshots you test efforts.

**Comment by execodess** [comment]
![IMG_2756](https://github.com/user-attachments/assets/d9578215-1181-4ac3-8b0f-80fa28cce3bb)

Tonkeeper doesn’t open (it opens after the second try) 

The connection confirmation window doesn’t open
